name: build
on: [push, pull_request]
jobs:
  test:
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: xvfb-run -a npm run test
        if: matrix.os == 'ubuntu-latest'
      - run: npm run test
        if: matrix.os != 'ubuntu-latest'
